<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Umbraco.Cms" Version="17.0.0" />
    <PackageReference Include="Umbraco.Cms.Persistence.Sqlite" Version="17.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Our.Umbraco.CropGuard\Our.Umbraco.CropGuard.csproj" />
  </ItemGroup>

</Project>
